### PR TITLE
Fix occasional git config error

### PR DESCRIPTION
**Pull request by derekcicerone**
I'm seeing an error during setup like this sometimes:
```
error: could not lock config file /Users/username/.gitconfig: File exists

/Users/username/actions-runner/_work/_actions/cardoe/ssh-agent-deploy-key/v1/webpack:/ssh-agent-deploy-key/node_modules/@actions/exec/lib/toolrunner.js:592
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
^
Error: The process '/usr/bin/git' failed with exit code 255
    at ExecState._setResult (/Users/seanmacisaac/actions-runner/_work/_actions/cardoe/ssh-agent-deploy-key/v1/webpack:/ssh-agent-deploy-key/node_modules/@actions/exec/lib/toolrunner.js:592:1)
    at ExecState.CheckComplete (/Users/seanmacisaac/actions-runner/_work/_actions/cardoe/ssh-agent-deploy-key/v1/webpack:/ssh-agent-deploy-key/node_modules/@actions/exec/lib/toolrunner.js:575:1)
    at ChildProcess.<anonymous> (/Users/seanmacisaac/actions-runner/_work/_actions/cardoe/ssh-agent-deploy-key/v1/webpack:/ssh-agent-deploy-key/node_modules/@actions/exec/lib/toolrunner.js:469:1)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12)
```

I think its because two git config commands are happening at once sometimes.

### CODE REVIEW

**Review by cardoe — APPROVED** [review]
Good spot. Thanks for the PR.

**Comment by derekcicerone** [comment]
Thanks for making this great action! The cleanup it does is really important for self-hosted runners.

**Comment by cardoe** [comment]
Absolutely that was one of the things I wanted to improve in this. Any other suggestions please feel free to PR or make an issue.

Need to `make dist` which I'll do in the morning.

**Comment by cardoe** [comment]
Bleh. I goofed in that push and it marked it as closed. But it was merged. I've also published a new v1.0.2 tag. I'll update the README with notes to run `npm run all` in your PR and commit the generated dist

**Comment by derekcicerone** [comment]
Sounds good, thanks for the quick update! I’ll try it out now.

**Pull request closed without merging**
